### ISSUE TITLE
new service references 28.2

### ISSUE THREAD

**Issue by leec32** [picons/picons-source#113]
hope this is in the correct place and done correctly, a few SRP refs for 28.2 have changed 

1845:7F3:2:11A0000=quest

1846:7F3:2:11A0000=questred

1840:7F3:2:11A0000=homeandhealth

1841:7F3:2:11A0000=discoveryturbo

183E:7F3:2:11A0000=discoveryscience

183F:7F3:2:11A0000=discoveryhistory

Thanks 

`donkey monkey got issued`

**Comment by AbuBaniaz** [comment]
It is on correct place. 
However, the links you have provided are in the wrong layout.
- Use the underscore instead of colon
- Put in code block so it is easier to copy and paste

I have added the links in this commit
https://github.com/picons/picons-source/commit/3b7483279bdbd8f69e62893ff25a64cade2e8888

**Comment by leec32** [comment]
noted for next time

thank you
