### ISSUE TITLE
Updated n-tv logo

### ISSUE THREAD

**Issue by tunip** [picons/picons-source#116]
Updated german n-tv logo since september.

logo:
http://logos.wikia.com/wiki/File:N-tv_Logo_2017.svg

srp-index:
```
2F3A_441_1_C00000=ntv
EF14_421_1_C00000=ntvhd
```

`donkey monkey got issued`

**Comment by Lexzie** [comment]
These srp-indexes are allready in srp-index.
What's missing is the srp-index for 9E.
Besides that the logo conflicts on snp with NTV Bangla and NTV Türkiye.
HD logo is not that best, I will give it a try to improve it.
Okay if I make a pull request for all these logos?

**Comment by Lexzie** [comment]
There is not really a typical HD-logo in use by the station. (Only 'HD' is shown in the upper left corner):

![afbeelding](https://user-images.githubusercontent.com/14023349/31454979-82e1f678-aeb7-11e7-821e-b08261a69914.png)


I beleive the HD addition to the standard logo you provided is just madeup by Unitymedia, not by the station itself.
I could not find a HD-logo in the website of n-tv for example.
So why not make it easy and just use one logo for both the SD and HD channel?

Just asking if that's okay since I am not one of the "core"-contributers here.

**Comment by tunip** [comment]
Yeah, that's fine with one logo for both SD and HD.

Thx

**Comment by Lexzie** [comment]
The ntv.light.svg is the same as ntv.white.svg
I think the ntv.default.svg looks okay on a black background, so no need for a ntv.light.svg
