### ISSUE TITLE
Feedback on logos. User on PLI wants to play a part

### ISSUE THREAD

**Issue by AbuBaniaz** [picons/picons-source#122]
A user on PLI forum would like to contribute to the project. He has provided these logos. Can you provide constructive feedback on them so that he meets the required standards please? (The names were modified when uploaded to the forum.)

I have provided him a link to the contributing guide. Sometimes a different/specific explanation is more beneficial.

Thanks in advance

[alex_NL.zip](https://github.com/picons/picons-source/files/504722/alex_NL.zip)

http://forums.openpli.org/topic/44032-how-to-use-the-extention-with-snp-picons/

**Comment by charlesduco** [comment]
None of the logos in the zip are acceptable because we have svg-versions of the hbo logos already in the repository.

If only the colour is different from an existing svg logo, you can adapt the svg logo with [Inkscape](https://inkscape.org/en/) or [Adobe Illustrator](http://www.adobe.com/products/illustrator.html) or even a simple text editor if you have knowledge of html and xml cause svg is just an xml-variant.

If svg editing is too difficult for you, you can also explain in this issue what exactly is wrong or missing in this repository. Other contributors with more knowledge and experience can offer to fix these imperfections and add a zip archive or git commit with the fixed logos.

Don't forget to follow the [contributing rules](https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md) when providing logos and entries to snp-index/srp-index

**Comment by AbuBaniaz** [comment]
Many thanks for your response and feedback.
