### ISSUE TITLE
Investigation Discovery Europe

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#134]
This channel on Astra 4A (4.8°E), 12322 V and on Thor 5 (0.8°W), 11341 V has a different logo:
![afbeelding](https://user-images.githubusercontent.com/14023349/31587800-40ff16f8-b1e8-11e7-8ffa-febbb4510b30.png)

[Investigation Discovery Europe.zip](https://github.com/picons/picons-source/files/1385699/Investigation.Discovery.Europe.zip)

It resembles this logo:
http://vignette3.wikia.nocookie.net/logopedia/images/a/ac/Investigation_Discovery.png

**snp-index**
```
ideurope=investigationdiscoveryeurope
idinvestigationdiscovery=investigationdiscoveryeurope
```
**srp-index**
```
12C_1_5E_30B022=investigationdiscoveryeurope
12D_1_5E_30B022=investigationdiscoveryeurope
1C05_2B_46_E080000=investigationdiscoveryeurope
```
`donkey monkey got issued`

**Comment by mocram** [comment]
This issue is incorrect, no where in the logo do the words `europe` show up, so it's a mystery for me why you would think it would be a good idea to include it the name.

I have nothing against typing, but I'm not a parrot. Please see your previous PR and my walls of text https://github.com/picons/picons-source/pull/120

**Comment by Lexzie** [comment]
So, you'd rather type ten random characters than six characters which exactly tell you what the logo is for?

**Comment by Lexzie** [comment]
Have it your way..

**snp-index**
```
ideurope=investigationdiscovery-cukawakifr
idinvestigationdiscovery=investigationdiscovery-cukawakifr
```

**srp-index**
```
12C_1_5E_30B022=investigationdiscovery-cukawakifr
12D_1_5E_30B022=investigationdiscovery-cukawakifr
1C05_2B_46_E080000=investigationdiscovery-cukawakifr
```

**Comment by AbuBaniaz** [comment]
> So, you'd rather type ten random characters than six characters which exactly tell you what the logo is for?

The reason we used the password generator for the bit at the end of logo names to distinguish them is that there was a problem with using country names/abbreviations before.

**Comment by mocram** [comment]
@Lexzie All of this "bullshit" according to you, is not just for the fun of it. It's hard explaining everything to a noob, but when you've been creating picons for 6 years and have come across several problems along the way, you might understand.

This particular logo was even used a few years back by all the Investigation Discovery channels, so it has absolutely nothing to do with europe, just a channel that has europe in its name is using an outdated logo.

I'm not sure why you insist on making up your own rules? Try looking at all the picons and all the channels out there and how they are linked, you'll soon see, it's not something invented for the lolz.

But we do appreciate that you finally see the light and will let us have it "our way", because, that was kinda the whole point.

**Comment by mocram** [comment]
@charlesduco @AbuBaniaz Do you guys think we should bother with this issue, since the OP can't be bothered supplying even two correct logo's and name them correctly, for the light version he was even too lazy to make all the text white, instead he just cropped it of. Even the cropping failed miserably, could not even bother to remove all abundant space.

Fuck it, I'm closing it, Feel free to re-open if you guys feel like it.

**Comment by charlesduco** [comment]
I think I fixed this.

**Comment by Lexzie** [comment]
I didn't "just cropped it", I see the default version still has the whole text below, shouldn't be there.
And again, I opened this as an issue since I'm not capable of making correct logos I let you guys do it (or let you just say 'fuck it' because you don't receive all the channels I do and can't be bothered by the abundance or incorrectness of the logos there)*. 
*(This is just a comment that it's kinda rude to address someone in that way).
And I don't see where all the abundant space is.

Hereby both logos as I intened it and now with zero pixels left at the borders.
[Investigation Discovery Europe.zip](https://github.com/picons/picons-source/files/1398124/Investigation.Discovery.Europe.zip)


On the lower left side of the 'I' there's 5 pixels space between the 'I' and the border of the picture, you mean that? Other margins are 1 and 2 pixels, sorry I didn't see that.
You'll probably mean something else?

**Comment by mocram** [comment]
@Lexzie Sigh, just stop with all the arguing and disrespect please! And once again you completely ignored everything I said and just named them `......europe.....png`. The logos were ok!

**Comment by Lexzie** [comment]
Ah, damn! You're right about the filename! That shouldn't have happened.

**Comment by mocram** [comment]
All is forgiven.

We don't mean to be dicks, but if we aren't, this thing is a complete mess in no time.

**Comment by Lexzie** [comment]
Oké, that's understandable.
Thanks!
