### ISSUE TITLE
Logo request

### ISSUE THREAD

**Issue by AbuBaniaz** [picons/picons-source#14]
Another logo request
Another raid of https://github.com/Jasmeet181/mediaportal-uk-logos repository

I have renamed them to our names. Hope it is done correctly. Please conform if his "dark" is our "light" version.
[20170416_logos.zip](https://github.com/picons/picons-source/files/924703/20170416_logos.zip)

**Comment by AbuBaniaz** [comment]
I also got these from here
```
http://www.beinsports.com/en/tv-guide
```
[20170417_bsports.zip](https://github.com/picons/picons-source/files/924701/20170417_bsports.zip)

**Comment by mocram** [comment]
This is not OK, disneyjunior.light should be default, frontrunner doesn't even need two versions.
Only channels and tv99 seem OK

```
default=standard logo as used by the tv station, looks good on background intended by tv station
light=modified default logo that makes darker parts lighter, looks good on darker backgrounds
dark=modified default logo that makes lighter parts darker, looks good on lighter backgrounds
white=fully white logo, no colors allowed (indexed 1-bit, black/white), looks good on dark backgrounds
black=fully black logo, no colors allowed (indexed 1-bit, black/white), looks good on light backgrounds
```

**Comment by AbuBaniaz** [comment]
I am useless at logos. Can you commit the good ones please?

Shame about others as we only have png files in our collection.

**Comment by Jasmeet181** [comment]
Mocram, I know that's in your Contributing document but there but in practise only default and light are in use, and defaults have been modified to make light parts darker. If @charlesduco could confirm whether that's what he's doing, then the document could be updated to reflect that.

Abu, the problem is with the renaming. Most MediaPortal skins are dark so light logos are my default (the dark ones aren't distributed in the plugin) so when there is a '- Dark' variation in my repository:
My 'Disney Junior.svg' becomes disneyjunior.light.svg here
My 'Disney Junior - Dark.svg' becomes disneyjunior.default.svg here
You're doing them the other way around.

With their current branding Front Runner use a [translucent R](http://www.information.tv/wp-content/uploads/2016/04/FR-Sport-Logo-white.png). They use the darker logo in some of their promotional material e.g. [Facebook](https://www.facebook.com/frontrunnertv/photos/a.1667579990223792.1073741826.1667578173557307/1695062720808852/?type=3) and [Twitter](https://twitter.com/frontrunnertv); and flatten the translucent logo to [this](http://www.information.tv/wp-content/uploads/2016/04/frontrunner_1100.png) elsewhere, including the [Freeview website](https://www.freeview.co.uk/why-freeview/channels/front-runner). All three are in the TV/Source folder in my repository, fwiw the flat lighter logo is the one I use in MediaPortal.

There's also a Showcase 3
[Default](https://github.com/Jasmeet181/mediaportal-uk-logos/blob/master/TV/Source/Showcase%203%20-%20Dark.svg)
[Light](https://github.com/Jasmeet181/mediaportal-uk-logos/blob/master/TV/Source/Showcase%203.svg)

**Comment by mocram** [comment]
@AbuBaniaz 

Just a simple rename should suffice :-)
default >> light
light >> default
...for the ones that are wrong.

**Comment by mocram** [comment]
@Jasmeet181 

Not sure what you mean? How should the doc be updated? To reflect what?

**Comment by Jasmeet181** [comment]
As far as I can see black, dark and white logos don't actually exist in the build-source and if needed default logos get modified as described under dark.

**Comment by mocram** [comment]
They are indeed not there, but it's possible to add them, for example for LCD receiver displays(black/white), the fact that default logos are being modified, is perhaps a lack of enforcement to force "dark" versions.

**Comment by AbuBaniaz** [comment]
Renamed. hope they're OK now.
[20170418_logos.zip](https://github.com/picons/picons-source/files/927023/20170418_logos.zip)
