### ISSUE TITLE
Picons not named correctly

### ISSUE THREAD

**Issue by Jacky2611** [picons/picons-source#162]
Hi there!

Just finished my tvh/oscam built and now I am trying to add some good looking picons. (namely the light on transparent, highest res) However, as far as I can tell many picons are either missing or named incorrectly.

I started with srp picons and while a few (e.g.: BBC europe, ...) did work at least 80% where not found. (most of my channels start with 1_0_19_... and there isn't a single picon included that starts like this) Considering that it was never mentioned if this pack supports Astra 19.2e I switched to the snp version. Problem is that A: all the names are lowercase without spaces (which means that tvh can't find them) and B: many picons are either named incorrectly or are missing altogether. (yep, I did browse through all of them one by one...)

I found this problem mostly with channels from Austria and Germany. Am I the only one? If anyone needs them I can list specific examples.

**Comment by charlesduco** [comment]
Did you follow this guide? https://github.com/picons/picons-source#tvheadend-servicelist-creation

Seems like you're doing something wrong because most picons for Austria and Germany are present in this repository.

**Comment by mocram** [comment]
For tvh you can't use SNP, tvh hasn't implemented SNP picons.
You should use SRP, however the picons from the downloads aren't build against a channellist, so all the picons start with 1_0_1, for Enigma2 receivers, this isn't a problem because when they can't find 1_0_19, they falllback to 1_0_1. Again, tvh hasn't implemented this fallback.

So the only way for you to get working picons is by:
1) Rename every picon (NOT RECOMMENDED)
2) Build them yourself against your tvh channellist, this way they will have the correct 1_0_19 when needed and you only end up with the picons needed for your channellist.

After being able to configure tvh+oscam, building the picons yourself is childs play.
