### ISSUE TITLE
[WIP] Italian and Swiss channels

### ISSUE THREAD

**Issue by picons** [picons/picons-source#2]

**Comment by udK** [comment]
WTF is going on here?!
What's happened to all the comments?

**Comment by mocram** [comment]
Well, I came up with the great idea of switching to Git LFS https://git-lfs.github.com/
Although it worked as expected, I was under the assumption that only my own pushes were being substracted from my allowed monthly free usage, but when I woke up and I saw that I already whas gone thru my bandwidth, I realized this was not the case.
So I had to revert the changes, the quickest way to completely get rid of all LFS traces was to just delete the repositories, because I got some errors reverting the commits.

**Comment by udK** [comment]
**Update SNP:**
~~privatetv=daringtv~~ -> privatetv=privatetv (logo: http://goo.gl/C7XrLh)

**Add SNP:**
daringtv=daringtv
