### ISSUE TITLE
Picons for IPTV channels ?

### ISSUE THREAD

**Issue by Arkoth79** [picons/picons-source#217]
Hello,

Can I submit "issue" for some picons for IPTV channels in the SNP project ?
example: 1 logo and 1 line in snp-index => 1 picon ;)

It's IPTV, so no srp-index...

Are you ok for this ?

Thank you in advance for your answer.

**Comment by charlesduco** [comment]
I'm not sure about snp-index. I don't use snp-index myself cause channels with the same servicename sooner or later get a wrong logo.

But there is a way to get srp-index working with IPTV channels, but you have to add the service references yourself, for example with a enigma2 channellist editor like DreamBoxEdit.
I am experimenting with the service references from OpenPLi user doglover: https://forums.openpli.org/topic/40312-iptv-channels-service-ref/ and this works for me.

I have no problem with adding these kind of IPTV-references to srp-index.
Maybe @mocram has another suggestion or idea?

**Comment by Arkoth79** [comment]
First, thank you for your very fast answer.
Ok cool ! I don't know if you will be ok for IPTV, now, I know and with your details I know howto do it too.

I use OpenPli so it's exacly what I mean and I know howto use dreamboxedit or dreamset... so, I think I can do it ^^ I hope ^^ I will see (when my kids let me do it... no comment LOL)

I will create issues with IPTV channels next days.

You can close my issue if you want, or if you want @mocram answer too, no problem.

An other time, thank you for your answer and details @charlesduco .

**Comment by mocram** [comment]
I agree with whatever @charlesduco thinks is best, I have no experience with IPTV at all...I don't even have any experience anymore with regular sat tv, turned the box on 2 times in all of 2016 :-)

But if I'm guessing right, you have to invent some servicerefs for IPTV? Well if this is the case try to keep it to one, not that everybody is going to add his own little made up serviceref.

Perhaps, create and md5sum/sha1 of the IPTV URL, take the maximum allowed letters/numbers of a serviceref, put in an underscore at the right spots.... That way you get some consistency....

**Comment by Arkoth79** [comment]
I will try... I'll keep you informed... in any case if it works or not ^^

I have a vmware with an ubuntu 64 and I already launch the script to test it before posting my issues...
So I will do same for IPTV to see howto do this, if it's working that would be great ^^ and with *-full option to be in the download section of the website for everyone ^^

@mocram Thank you for your idea (md5/sha1) but I don't think it will work with srp-full option with 2-build-picons.sh because in the file create-symlinks.sh it will do : **1_0_1_**"$unique_id"**_0_0_0.png** and it's not the good srf _I think_ to work with IPTV. 

It was for this reason, I suggested to use SNP with snp-full option... with 1 svg in logo and 1 line in snp-index
I understand that you prefer SRP... but...

I've just tried dreamboxedit, all the IPTV channels are : 1_0_1_0_0_0_0_0_0_0
nothing with dreamset...

from the link from @charlesduco in the 2nd post from doglover:

> When you add a stream to your Enigma-box, they all have the same reference ID.
(4097:0:1:0:0:0:0:0:0:0:)
So, adding picons or EPG would not work.

> 

An example for IPTV channel  : [https://fr.wikipedia.org/wiki/SFR_Sport_1](https://fr.wikipedia.org/wiki/SFR_Sport_1)
It's a french iptv channel from the ISP called SFR in France.

We will see ^^

Thank you for your help

**Comment by AbuBaniaz** [comment]
> I don't use snp-index myself cause channels with the same servicename sooner or later will get a wrong logo and you'll have to fallback to srp-index to get the right logos for all channels.

Same applies to SRPs when channels change name or an abandoned reference is re-issued.

The SNP code within images gives preference to SRPicons over SNPicons. You would only need to give the service references for the channels that clash, rest will use the named version.  Pretty sure that the SNP code will work for IPTV channels too although I have not tried. 

This project allows you to have both SRP and SNP links. Need to get some freetoair IPTV links to try.

**Comment by charlesduco** [comment]
Good, we'll try with snp-index like @Arkoth79 suggested.

**Comment by mcfly822** [comment]
SNP is working for IPTV, at least on my box it is perfect. The channel name what I give to the stream (i can rename easily in dreamboxedit) determines which picon is used.

**Comment by mocram** [comment]
@Arkoth79 I was under the assumption that you could also modify the service reference used by iptv streams, with something like dreamset...

So if that would be the case I suggested to do something that could be duplicated by everyone, not that we would create a situation where every user using iptv would come and ask us to add their own made up serviceref based on the weather.

To be honest the whole idea of a serviceref for picons has been flawed from day 1, but it's what we have been given. A few years back I made a suggestion to pick a limited amount of info like `name, sat/cable/iptv, ...` turn that in to a hash and use that, but use as much info to make it unique, but not too much so that it changes every day.

It doesn't exist yet, so I guess I was the only one who thaught it was a good idea.

**Comment by mocram** [comment]
Is @Arkoth79 still alive or has he been captured by ISIS? Either way since he doesn't care anymore we perhaps have to close this issue?

**Comment by Arkoth79** [comment]
@mocram yes still alive, thank you for your concern.
you can close the issue.

**Comment by mocram** [comment]
Good to know you are not dead. :-)

**Comment by Arkoth79** [comment]
@mocram 
You write without respect many times ... What have I done against you?

For the iptv, see issue #220 for French channels, it works perfectly.

I do not understand your condescension and why you write "ISIS" or if I'm alive ... 
This issue was to know if the project can do picons for IPTV... just that. And howto.

I understand the issue can be closed before when I had the answer, and it could been said otherwise.

"I don't even have any experience anymore with regular sat tv, turned the box on 2 times in all of 2016 :-)"
Indeed, there is more important in life: health, family etc ... than picons in my opinion.
That's why I do not understand how you write that is insulting.
Have a good day.

I will continue posting issues if necessary for me and my friends despite this without resentment.

**Comment by mocram** [comment]
I'm not trying to be condescending or anything at all. If I could have said it face to face you would have understood it was more or less meant in a funny way. This is sometimes hard to get across right when written and GitHub hasn't a lot of smiley face support.

What you consider without respect, I consider it straight to the point without a lot of unnecessary small talk.

I do however find a bit rude to start an issue, get a few people involved and not getting back to us, to let us know if the issue is resolved or it can be closed and an new issue will be made in due time. I understand life sometimes get in the way, but respect to the people who put a lot of work in these measily picons can't hurt.

**Comment by Arkoth79** [comment]
So much funny that you edited your text on "ISIS" on comment-289851285
My posts are not edited as you do to hide something...
No comment from me about this. It's not my problem.
Have a good day mocram ;) => smiley

**Comment by mocram** [comment]
You fucking moron, I edited that comment BEFORE you replied! Please fuck off!

**Comment by mocram** [comment]
@charlesduco @AbuBaniaz 
Please close any issue made by @Arkoth79 

For some reason the guy thinks we have to tiptoe around his precious feelings and instead of showing some respect, he likes poking the bear.

Full disclosure: I did remove the remark about ISIS before he posted that comment, for the only reason to not have this project related with that word. I re-added the comment, so that people know what's going on.
