### ISSUE TITLE
Official logo vs screen logo

### ISSUE THREAD

**Issue by mcfly822** [picons/picons-source#225]
Hello all,
I have a question for a long time. This problem occurs sometimes.
What if if a channel's official logo differs from the logo appears on the screen?
For example:

Discovery Science on screen logo:
![dsc_screen](https://user-images.githubusercontent.com/22531870/33744098-dd38318a-dbaf-11e7-8554-e01bdc8bb74e.jpg)

Discovery Science official logo:
![discoveryscience](https://user-images.githubusercontent.com/22531870/33743765-7249376c-dbae-11e7-8fc8-76b5b101058c.png)
and another variation:
![dsc1](https://user-images.githubusercontent.com/22531870/33743273-671effe0-dbac-11e7-84e5-62a379c24000.png)

Paramount channel screen:
![paramount_screen](https://user-images.githubusercontent.com/22531870/33743387-e78784b8-dbac-11e7-9787-01153fd67d38.jpg)
Paramount Official, which appears in this repo and also on the official website (in Hungary: http://www.paramountchannel.hu/)
![paramountchannel](https://user-images.githubusercontent.com/22531870/33743422-0e6ee454-dbad-11e7-98b8-bd40da7e648b.png)

Investigation Discovery screen:
![id_screen](https://user-images.githubusercontent.com/22531870/33743816-a7be3d52-dbae-11e7-81a6-06aa1d1c81eb.jpg)
...and the logo:
![investigationdiscovery](https://user-images.githubusercontent.com/22531870/33743847-d0836cb2-dbae-11e7-928a-a2f10add94c8.jpg)

So, in these cases, which logo should we use? The official or the 'on-screen'?

**Comment by mocram** [comment]
Whatever is used on their website and looks good on a white background, on screen logos often are greyed out logos.

**Comment by mcfly822** [comment]
Ok, the color is no problem.
But you can see, in the examples the text/shape is also different.

**Comment by mcfly822** [comment]
Another example, maybe the biggest difference.
The 'Fishing and Hunting Channel' has an official logo, which is also in this repo:
![fishingandhunting_repo](https://user-images.githubusercontent.com/22531870/33752606-04582044-dbe3-11e7-95b1-8262d0af95a1.jpg)
But on the screen, there is another logo, which is much better (and looks great on dark background. This is only my opinion):
![fishingandhunting](https://user-images.githubusercontent.com/22531870/33752630-2e26a2a6-dbe3-11e7-98af-1f4a15abf936.jpg)

If I would like to change the logo in the repo, then is this allowed?
What is the policy?

**Comment by mocram** [comment]
Whatever looks best...

**Comment by mcfly822** [comment]
Ok, thank you. But which looks 'best', this is very subjective :-) 
Like @AbuBaniaz has the opinion, that the sky logos would be better in two rows (I agree 😉 ) but for somebody, it is worse.
Ok than, if I'm not sure about a logo which has more variations, I'll ask the community.

**Comment by mocram** [comment]
I think, given the work you have delivered up until now, you are more than qualified to determine yourself what looks "best".

My personal "best"

1) something that looks good on white as the default logo, which most of them are, websites are mostly white
2) something that is preferably svg
3) something that is easy to find, we can't use anything if it does not exist

There are always going to be different variations for the same logo, like your Paramount Channel logo, I see no problem keeping the mountain, no point removing it because it's not shown on-screen. A visual mountain gives a better indication than some small letters from far away. If indeed the tv channels rebrand is entirely based on dropping the mountain, that's another story.

```
sky sports hd1 active & tennis
```
is always going to look worse when it's a small picon than
```
sky sports hd1
active & tennis
```
and given that the lenght stays overall the same, will give a better visual representation if a lot of them are listed in a row, the latter might even be readable, the first probably not.

Regarding the "rules", they are meant to get rid of the worst junk people like to submit, which in the beginning was just a png stolen from somebody elses picon set, so we got a bunch of 100x60 png's, because that was the easy way for the submitter, meanwhile a quick google search delivered +1000px png's or svg's. Obviously they did not see the point to deliver bigger resolution, because THEY only needed 100x60. If common sense says it's ok to bend the rules a bit....ok...this is not North Korea.

**Comment by mocram** [comment]
When looking at the website of http://www.paramountchannel.es/

I see 2 versions, the one at the top of the page will most likely look best on rectangle based picons, the logo's from the center of the page will probably look best when the picon is a square. Given that most picons are rectangle, I would pick the top one, square picons are used inside Kodi and are of sufficient size, so they can deal with the readbility issue a lot better. But, if I can easily find a svg of the logo in the middle of the webpage and not from the top one, I'll pick the svg.

**Comment by mcfly822** [comment]
> If common sense says it's ok to bend the rules a bit....ok...this is not North Korea

Haha 😆 

Ok, it is clear now. Everything you wrote was exactly what I'd like to know.
Thanks!

**Comment by mocram** [comment]
Another note about the above logo, you can see the logo is actually white, but this is not ideal for the default logo. But the "theme" is kind of blue, so I would make the logo just blue.

**Comment by mcfly822** [comment]
Yes, the color 'policy' was very clear after I added the new echotv logo some days ago, and you asked the color version for default.
Now the shape, text, etc. 'rules' are also clear for me.
I'll continue making/editing logos regarding your guideline above.

**Comment by mocram** [comment]
Beware bad quality mockup incoming....

![33752630-2e26a2a6-dbe3-11e7-98af-1f4a15abf936](https://user-images.githubusercontent.com/16463960/33760238-4f423866-dc05-11e7-87c4-43ccdafaa292.jpg)

I would not mind anything like this, if you insist updating it.

**Comment by mocram** [comment]
Regarding discover science, my personal favorite would be 
![33743273-671effe0-dbac-11e7-84e5-62a379c24000](https://user-images.githubusercontent.com/16463960/33760466-fe492644-dc05-11e7-90b2-16bfd13a1602.png)

because if I'm not familiar with the channel, I would not knwo what SCI means.
Naming the logo `sci.default.svg` would however be a big nono for me.

**Comment by mcfly822** [comment]
Paramount: I like better the existing logo, the mountain above and the text below...

Fishing&Hunting: I have vector files both for text and for other grapchic elements so I can modify and make something similar than you showed.

Discovery science: your favourite seems very good, but unfortunately not official. The arrangement of text elements and the font type also differs from the official.
I found one in vector format with text, just a little (color) modification was needed. I think it will be a bit better than the existing 'only SCI text' version.
[dscience_maybebetter.zip](https://github.com/picons/picons-source/files/1542549/dscience_maybebetter.zip)

**Comment by mocram** [comment]
Ah, so somebody made that logo on his own for discovery.... Well assuming it would have been an officially used logo by Discovery Science, I would have choosen that one.

Sigh, if only they could just stick to using the same logos, instead of switching every 6 months.

**Comment by dalmore72** [comment]
@mcfly822 Discovery science hd you can find here :)


https://www.upc.cz/pdf/pece-o-zakazniky/dokumenty/Cenik_Digital.pdf

**Comment by mcfly822** [comment]
@dalmore72 Thanks! (I know this pdf, I found it recently when I was searching for logos).
Discovery science logo modification coming soon 😉
