### ISSUE TITLE
Extracting Hispasat 4k logo from pdf

### ISSUE THREAD

**Issue by Lexzie** [picons/picons-source#286]
Can anyone extract the Hispasat 4k logo from this pdf:
[hispasat4k-pdf.zip](https://github.com/picons/picons-source/files/1657170/hispasat4k-pdf.zip)

It should be something like this:
![afbeelding](https://user-images.githubusercontent.com/14023349/35293703-cf113cca-0074-11e8-86d4-9df03b22b32c.png)

The links are:

**Add to snp.index**
```
hispasat4khevc=hispasat4k
hispasat4k=hispasat4k
```

**Add to srp.index**
```
1_3E8_3E9_CE40000=hispasat4k
1F5_69_53_CE40000=hispasat4k
```
`donkey monkey got issued`

**Comment by mcfly822** [comment]
@Lexzie sorry, the attached pdf is not good, because it contains the logo in embedded format. You can see it, when you open the pdf in inkscape, and if you zoom in, you see that the quality getting worse.
I extracted the logo from this pdf:
https://www.hispamar.com.br/contenidos/web/0/113-4k_en123.pdf
It is good, contains the logo in vector format.
(I hope you are not angry me, I just tried to help you :wink: )

[hispasat4k.default.svg_mcfly822.zip](https://github.com/picons/picons-source/files/1657396/hispasat4k.default.svg_mcfly822.zip)

**Comment by Lexzie** [comment]
Maybe that's why it couldn't be done by me.
Your svg look very good to me, can some one upload it and make the changes to the indexes?

**Comment by AbuBaniaz** [comment]
Thanks. Done.

**Comment by Lexzie** [comment]
Thanks
