### ISSUE TITLE
SRP output contains radio channels icons but no adequate links?

### ISSUE THREAD

**Issue by bibbs** [picons/picons-source#30]
despite seeing radio channel icons in the "logos" directory I cannot find any SRP files linking to them ...
(tested the enigma2 package)

Greetz, bibbs

**Comment by mocram** [comment]
By default radio channels will also get 1_0_1 at the beginning instead of 1_0_2 what is normally radio, when building against a channellist/servicelist the radio channels will start with 1_0_2.

This is a side effect of no longer making a clear distinction between tv & radio logos, which was causing us keeping duplicates.

I thought enigma2 would fallback to 1_0_1 also for radio, but apparently this is not the case, so if you are a big radio user, use snp version or build against a channellist.

OR ask a small code update to the following line of code (https://github.com/OpenViX/enigma2/blob/a2cff79d831bcfe2721898c6aea771274cf65e12/lib/python/Components/Renderer/Picon.py#L81) too also fallback for radio channels.

OR if somebody can do a full scan with a rotor and upload it to github on a weekly schedule, we could use that channellist instead.
