### ISSUE TITLE
SFR Sport 4 and L'équipe Tv new logo 

### ISSUE THREAD

**Issue by daviok** [picons/picons-source#349]
Hello,

Here the new channel from sport channel bouquet SFR "SFR sport 4", and the new logo for "L'equipe TV".
[logos.zip](https://github.com/picons/picons-source/files/1833756/logos.zip)

Add to srp-index

`2572_A0_1_FFFF0000=sfrsport4`

Add from snp-index and logos

```
sfrport4=sfrsport4
sfrsport4hd=sfrsport4
lequipehd=lequipe
lequipetv=lequipe
lequipetvhd=lequipe
```

delete from snp-index

```
lequipe21=lequipe
lequipe21sd=lequipe
```

`donkey monkey got issued`

thanks :)

**Comment by daviok** [comment]
do i forget something ?

**Comment by mcfly822** [comment]
@daviok wrong named files inside the zip.
https://github.com/picons/picons-source/blob/master/.github/CONTRIBUTING.md

> Logos should be inside an archive, **correctly named** (see below). Share the link.

Naming:

> LOWERCASE
NO spaces, fancy symbols or .-+_*, except for the exceptions below.
Time sharing channels are seperated by _.
If the logo name you wish to use already exists, add a unique identifier like -trechuhipe, this is a pronounceable random 10 character string generated using this password generator. Grouping logos together using the same unique identifier is possible.
Filetype svg is the way to go, otherwise png.
The resolution doesn't matter for svg, for png try to get it > 800px.
When submitting svg files, make sure to convert text to paths.
It's not allowed for svg files to contain base64 encoded images.
Try to make svg files rsvg compatible, they definately need to open in Inkscape, so no Adobe Illustrator only compatibility.
If it's possible to easily trace your png with Inkscape, only the svg is allowed. In most cases this is possible.
Quality should be as high as possible.
Background should be transparent.
No empty space around the logo.
A default version of a logo should get the identifier .default at the end of the filename, additional types are possible, by using for example .light, .dark, .black or .white as an identifier.

**Comment by daviok** [comment]
[logos_lequipe_sfrsport4.zip](https://github.com/picons/picons-source/files/1833216/logos_lequipe_sfrsport4.zip)

**Comment by daviok** [comment]
ok edited first post

**Comment by AbuBaniaz** [comment]
The logo has changed, that does not mean we need to rename it.

You cannot delete what does not exist.
```
lequipe21=lequipe
lequipe21sd=lequipe
```

 The links are actually as below. If the channel does not exist now, we can delete them and the logo

```
lequipe21=lequipe21
lequipe21sd=lequipe21
```

**Comment by AbuBaniaz** [comment]
The sfrsport4 logos in above commit were made from the existing sfrsport4k ones. I have added them, they need to be trimmed.

**Comment by daviok** [comment]
ok thanks :-)

**Comment by AbuBaniaz** [comment]
We have two different logos, meaning two different channels.

Please close the issue if everything is OK

**Comment by Lexzie** [comment]
You made a typo.

**Please delete from snp.index**
```
sfrport4=sfrsport4
sfrporthd4=sfrsport4
```

**Please add to snp.index**
```
sfrsport4=sfrsport4
sfrsporthd4=sfrsport4
```

`donkey monkey got issued`

**Comment by daviok** [comment]
oh yea sorry Lexzie

**Comment by Lexzie** [comment]
No problem, just helping.
I noticed still no logo in my list of Eutelsat 5 West A.
Great work adding these logos!

**Comment by AbuBaniaz** [comment]
>I noticed still no logo in my list of Eutelsat 5 West A.
What do you mean please?

**Comment by Lexzie** [comment]
That I noticed that a day ago. I'm sure it's okay now (did not check yet).

**Comment by AbuBaniaz** [comment]
Logo's get added to the repository and can be checked instantly. Please explain what logo you are waiting for.

**Comment by Lexzie** [comment]
None, I just replied to daviok's message.
