### ISSUE TITLE
20 Mediaset logo

### ISSUE THREAD

**Issue by secuflag** [picons/picons-source#402]
This logo should be a bit rechecked because it's missing the "MEDIASET" under the logo.

See here: https://it.wikipedia.org/wiki/File:20_Mediaset_Logo_2018.png

Screenshot from live streaming: ![20180506-123356](https://user-images.githubusercontent.com/372417/39672516-aa413438-512b-11e8-9492-7206a4c8ea37.png)

Please someone could modify of this because I'm not good in graphic at all.

Thanks.

**Comment by Lexzie** [comment]
You're right because it is what is shown on screen, but I'm in doubt because it just makes the actual logo smaller, so less visible.

![20 mediaset hd-list](https://user-images.githubusercontent.com/14023349/39673031-38aff62e-5135-11e8-9b45-2b86ba1a5b92.jpg)
![20 mediaset hd-list new](https://user-images.githubusercontent.com/14023349/39673032-38d13906-5135-11e8-8f91-f275898983d5.jpg)
![20 mediaset hd-nownext](https://user-images.githubusercontent.com/14023349/39673033-38f23f66-5135-11e8-87fc-f7a32a7b762e.jpg)
![20 mediaset hd-nownext new](https://user-images.githubusercontent.com/14023349/39673034-390d19f8-5135-11e8-9d83-7817556b1e23.jpg)

![20 mediaset-list](https://user-images.githubusercontent.com/14023349/39673058-c6772996-5135-11e8-80f5-e43ec56f2a05.jpg)
![20 mediaset-list new](https://user-images.githubusercontent.com/14023349/39673059-c6916e32-5135-11e8-8878-5c9bba9d9f8d.jpg)
![20 mediaset-nownext](https://user-images.githubusercontent.com/14023349/39673060-c6ab4e1a-5135-11e8-9afd-9eb0c163cd4c.jpg)
![20 mediaset-nownext new](https://user-images.githubusercontent.com/14023349/39673061-c6c5b354-5135-11e8-8593-312230b3b82e.jpg)


I am curious what other think of this.

**Comment by mcfly822** [comment]
Maybe I'll be alone with my opinion, but it is better if a picon match the real logo even if it results a smaller picon.
So one vote for the logo with 'mediaset' text.

**Comment by TheLegoBatman** [comment]
I think most of us prefer the logo to match the original logo as closely as possible.

**Comment by Lexzie** [comment]
I'm neutral. So no votes against (yet).

**Comment by secuflag** [comment]
Thanks!
