### ISSUE TITLE
24 Kitchen New Logo

### ISSUE THREAD

**Issue by rubix86** [picons/picons-source#403]
here the new logo for 24 Kitchen HD can you make SD picon too from it
side note: I only check the dutch version I did not check other versions on other satellites 

![24_kitchen_hd_ 2016- n v](https://user-images.githubusercontent.com/17280907/39678350-48f6b378-518b-11e8-88e6-239aaf16a6b6.png)

**Comment by TheLegoBatman** [comment]
It didn't change for Hispasat at least. Can you get us the frequencies or direct us to the right package where it has changed please? I will get this sorted tomorrow unless somebody else gets to it first.

**Comment by Lexzie** [comment]
I found a svg for this logo, so we go with that one and not the png. (Probably could have made it too, if I can find the correct font).
I will make both the SD and HD logo if that's okay.
But if other countries have not changed (yet?) we need to keep the old logo as well.
As far as I can see the Bulgarian, Croatian and Serbian versions haven't changed too.

@rubix86 From which provider do you get the dutch version? If it's not on satellite, Ziggo, Delta or Digitenne can you give me the snp- and srp-links you recieve?
@TheLegoBatman Same for the Hispasat stations (both NOS and MEO). Due to leaves on a tree I cannot receive Hispasat in the spring/summer.

**Comment by TheLegoBatman** [comment]
It is sorted. Just waiting on the pull request being accepted.

**Comment by TheLegoBatman** [comment]
Please close this issue.
