### ISSUE TITLE
1-build-servicelist.sh stops in output when unicode characters are present in tvheadend 

### ISSUE THREAD

**Issue by pe2mbs** [picons/picons-source#432]
Whenever a channel name contains unicode character(s) the output file srp is cut-off. 
Some examples of unicode names
   Laâyoune = picon://1_0_2_5A_2E18_B0_820000_0_0_0.png
   MDR THÜRINGEN = picon://1_0_2_6F0E_445_1_822FFC_0_0_0.png

I replaces manually the unicode characters, then the full srp file is generated correctly.

If you need more info, let me known i'll provide it when i can :-)

**Comment by mocram** [comment]
If I recall correct this has already come up a few times in the past, wasted a lot of time too on the matter... I think it was because of bad/incorrect local configuration.

Enigma2 surely has unicode characters too, nothing wrong for lots of people.

So unless there are some logs or you can tell me exactly where the fault lies, I'm gonna have to close this issue.

**Comment by pe2mbs** [comment]
To which character set tvheadend should be configured ?, currently now its set to AUTO
