### ISSUE TITLE
service type incorrect with srp_full?

### ISSUE THREAD

**Issue by espiman** [picons/picons-source#46]
Hi.

Great tool, thanks in advance.

If I download only tvheadends channels with srp option, SD channels picon are 1_0_1_xxxx and HD channels picon are 1_0_19_xxx, like appear in file servicelist-tvheadend-servermode

Ex:
1_0_19_7861_41A_1_C00000_0_0_0     |  BEIN MAX 1            |  7861_41A_1_C00000=beinsportsmax1hd
1_0_19_7864_41A_1_C00000_0_0_0     |  BEIN MAX 2            |  7864_41A_1_C00000=beinsportsmax2hd
1_0_19_750E_420_1_C00000_0_0_0     |  BEIN MAX 3            |  750E_420_1_C00000=beinsportsmax3hd
1_0_1_757C_412_1_C00000_0_0_0      |  BEIN MAX 4            |  757C_412_1_C00000=beinsportsmax4
1_0_1_757D_412_1_C00000_0_0_0      |  BEIN MAX 5            |  757D_412_1_C00000=beinsportsmax5
1_0_1_769D_41E_1_C00000_0_0_0      |  BEIN MAX 6            |  769D_41E_1_C00000=beinsportsmax6
1_0_1_769E_41E_1_C00000_0_0_0      |  BEIN MAX 7            |  769E_41E_1_C00000=beinsportsmax7
1_0_1_7576_412_1_C00000_0_0_0      |  BEIN MAX 8            |  7576_412_1_C00000=beinsportsmax8

But, if I download srp-full, all the downloaded picons are 1_0_1_xxxxx, is rigth?

Thanks.

Best regards.

**Comment by mocram** [comment]
Yes, this is correct. srp-full isn't build against a channellist so it's not possible to know wether to take 101 or 1019, even for radio (=102), 101 is used, wich at this moment also gives wrong results on Enigma, because it doesn't fallback to 101 for radio.

Some months ago I was building against an actual channellist, so 1019 was used where needed, but since that list didn't contain all the channels, lots of channels were missing, it was also a nightmare(slight exageration) to keep updating the channellist. So I compromised and for most Enigma2 users it's OK.

But, if you want the most correct output files, it's best to build them yourself and not that hard for users that are able to setup a htpc using Kodi, TvHeadend/VDR, afterall they have a Linux machine ready to use.
