### ISSUE TITLE
[Add] Mediaset Premium Sport 2

### ISSUE THREAD

**Issue by udK** [picons/picons-source#47]
Add in **snp-index**:
`mediasetpremiumsport2=mediasetpremiumsport2` 

(http://www.mediasetpremium.it/assets/images/channels/KC.svg)

Thank you!

**Comment by mocram** [comment]
https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md

**Comment by udK** [comment]
What's wrong?

**Comment by charlesduco** [comment]
There is already an hd logo for this channel in the repository, named `mediasetpremiumsport2hd`.
It's not clear whether an sd logo should be added or there is an error in your entry to snp-index.

**Comment by udK** [comment]
The channel Mediaset Premium Sport 2 is available in HD and SD, we already have the HD logo but not the SD version.

**Comment by mocram** [comment]
The way I see it...

You're asking me to add `mediasetpremiumsport2=mediasetpremiumsport2` to snp-index, using the logo of mediasetpremiumsport2**hd**.

The correctly named logo is not in a zip file in this case.

I can also assume that you want me to link it like `mediasetpremiumsport2=kc`, in this case the svg should be called kc.default.svg.

**Comment by mocram** [comment]
```
When submitting an issue, make sure you follow these rules:

Entries to srp-index or snp-index, put them inside code blocks by using backticks (help) or if they are really big, use a gist.
Logos should be inside an archive, correctly named (see below). Share the link.
```

In case no archive/zip file is found in an issue, I'm assuming that every entry provided for srp-index and snp-index already has a corresponding logo, if no logo exist, it shoud be added to the issue using a zip file. Keep in mind that the logos inside the zip file need to be 100% following the other rules.

A correct filed issue, would only require 2 copy/paste commands and a one time extraction of an archive.

If this is beyond the scope of your abilities, just create an issue that you are missing the logos A, B and C and that you found some samples that you can link to which sort of make clear how the logo should look like. Now just wait until you see some commits containing your logos and use those names to create a new proper issue for the srp-index and snp-index.

I'm not trying to be an ass here, but in your head your issue makes perfect sense, now just follow the rules so that it also makes sense in our head. I no longer can count on both hands the times I wasted time creating the correct logo, just to realize that it already existed when putting it in the repository, just because somebody found it helpfull to remind me what the logo looked like.

So for you issue to be correct it had to contain an archive containing the logo `mediasetpremiumsport2.default.svg`.

If this was not possible, you should have asked:
```
At the moment there is no logo for mediasetpremiumsport2, only an HD version is available, can somebody create an SD version by cutting of the text "HD". Afterwards I will create an issue containing the correct additions to srp-index and snp-index if I don't see them in the commit.

```
If I read this, I know there's a useful logo available ready to use, probably commited by charlesduco, so I will not waste time using a different logo which might contain faults that charles already took care of.
