### ISSUE TITLE
About service 4097 streaming services

### ISSUE THREAD

**Issue by satrobinhood** [picons/picons-source#5]
There are some enigma2 channels that are not dvb but stream services
for dvb service list are for example 1_0_1_6D6E_437_1_C00000_0_0_0 but for stream service are 
4097_0_1_6D6E_437_1_C00000_0_0_0 change only 1st number from 1 to 4097.

On latests openpli images tested and picons working ok if png is something like this
4097_0_1_6D6E_437_1_C00000_0_0_0.png
Can we modify 1-build-servicelist.sh and 2-build-picons.sh for supporting 4097 stream services ?

**Comment by picons** [comment]
Could you upload a channellist containing those channels....

**Comment by satrobinhood** [comment]
yes i can give you an example.
1) edit bouquets.tv and put this line

#SERVICE 1:7:1:0:0:0:0:0:0:0:FROM BOUQUET "userbouquet.freestream.tv" ORDER BY bouquet
2) make one file userbouquet.freestream.tv
and contains following
#NAME FreeStream
#SERVICE 4097:0:1:180:1CB4:13E:820000:0:0:0:mms%3a//media19.internet.gr/ParliamentTV-HQ:Gr Parliament
#DESCRIPTION GR Parliament

3) init 4 to stop enigma2 and
4) init 3  to startit again

now you have one iptv bouquet on favourites with name FreeStream

for this channel i have put service reference from 13E nova bouquet channel called Vouli (gr parliament)
and want on those services to use picons only difference from sat channels is that starting with service 4097: and not 1:

Regards

**Comment by charlesduco** [comment]
Picons for IPTV streams are already supported in OpenPli, it's done done through the service name instead of the service reference cause streams have no dvb service id's.
You just need to put the service name in the bouquet list like you did for "Gr Parliament":

Then you put a picon with filename "grparliament.png" (lowercase, trimmed spaces) in the directory /picon and you're done.

More info in this topic: http://forums.openpli.org/topic/35628-picons-by-service-name/

So, if this would be implemented in picons-source, it should be done by the service name.

**Comment by picons** [comment]
Ok, a couple of remarks for future reference:

-For the love of god, try to use code blocks.
-If I ask to upload a channellist containing the info I need, I don't expect a user manual on how to create one from scratch.

I've pushed an update which can deal with the 4097 part.

**Comment by satrobinhood** [comment]
Sorry for that.
Was 1st time that use github.
Will nevet happen again.

From iphone

13 Μαρ 2015, 7:14 μ.μ., ο/η picons <notifications@github.com> έγραψε:
