### ISSUE TITLE
Add some channels (SNP)

### ISSUE THREAD

**Issue by Silverscape** [picons/picons-source#65]
Please add SNP icon for "Mooz Dance" and "Mooz Dance HD".

There is already a SRP icon called "1_0_1_2AF9_B_1111_E082F3C_0_0_0.png".
Please copy that icon for "moozdancehd.png" and also for "moozdance.png" (same icon for HD and SD).
Thanks.

**Comment by mocram** [comment]
There's no need to give us instructions on how to do our job, because there's no copying of png files required.
It was probably however a good idea to read https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md
I'm not going to write this response in every issue that you created, do you also write 10 complaint mails to your tv manufacturer if 10 remote buttons are faulty, or just one?

**Comment by Silverscape** [comment]
Sorry, my fault.

orf2nhd=orf2hd
30DE_413_1_C00000=fashion4k
78B8_2C5_600_E080000=viasatexplore
2AF9_B_1111_E082F3C=moozdancehd
2AF9_B_1111_E082F3C=moozdance

Is that better?
