### ISSUE TITLE
Pick a for dvb-c unitymedia / tvheadend note generated

### ISSUE THREAD

**Issue by foobar270** [picons/picons-source#69]
Hi,

I can't get picons generated for this file:
http://paste.debian.net/297425/

Any idea what is going on here?
Only suspicious message I see during 2nd step generation is this message:
17:18:06 - Creating picons: srp.100x60.black-white
   usage:  pngquant [options] <ncolors> [pngfile [pngfile ...]]
                    [options] -map mapfile [pngfile [pngfile ...]]
   options:
      -force         overwrite existing output files
      -ordered       use ordered dithering (synonyms:  -nofloyd, -nofs)
      -verbose       print status

This is repeated.
Thx M.

**Comment by picons** [comment]
What OS are you using?

It seems that on your system `pngquant -` isn't working, as a workaround you can replace `compress="pngquant -"` with `compress="cat"`. This way pngquant isn't used and the picons will be 24bit instead of 8bit.

I tried to build your servicelist and it's working as expected on Cygwin for Windows.

If I get all your OS details, I can try to find a way to work around the problem.

**Comment by foobar270** [comment]
The OS is a debian chroot (wheezy) on a synology NAS 
(Linux 3.10.35 #5592 SMP Wed Jul 29 14:40:42 CST 2015 x86_64 GNU/Linux)

Generally I do not have any issues with this setup - run all sorts of apps within this environment.

Indeed your workaround does work.

**Comment by picons** [comment]
I'm not sure how relevant this (https://github.com/rflynn/imgmin/issues/26) still is, but if debian still indeed has an old version, I would recommend to just keep using the `cat` workaround or try updating pngquant, by using cat the files are a bit bigger, but you have the best quality, since you are using tvheadend, I don't think size really matters for just +/- 200 channels.

The versions I use to test are:

```
Cygwin - pngquant, 2.3.4 (September 2014)
Ubuntu 14.04.3 LTS - pngquant, 2.0.1 (September 2013)
```

Previously `cat`, which basically means to not use pngquant in the script, was the default for kodi, but because of switching to pngquant from pngnq and I couldn't see a real difference so I also enabled it for kodi.

The problem on your system seems to be that pngquant doesn't seem to be able to read from the pipe with the use of `-`. If that's a bug in an old version of pngquant or some compatibility issue with your system, I'm not sure.

Since that Debian Wheezy is such an old OS already, I'm not going to invent all sorts of workarounds, if it's easily solved by using `cat`.

I try to keep supporting Cygwin on Windows and a recent version of Ubuntu. Most of the times this means that quite a few other distros work just fine.

**Comment by foobar270** [comment]
I did go through the hassle of an upgrade today - and indeed with the latest Debian jessie release the problem is gone.
Thanks for looking into this.

**Comment by foobar270** [comment]
I did go through the hassle of an upgrade today - and indeed with the latest Debian jessie release the problem is gone.
Thanks for looking into this.

**Comment by picons** [comment]
Good that it is solved, welcome back to the year 2015 :-)
