### ISSUE TITLE
Help to add channels

### ISSUE THREAD

**Issue by gurabli** [picons/picons-source#73]
I would like to contribute by adding the missing picons for Thor 0.8W two Hungarian providers. Lot of them needs to be updated and there are new channels too.

I would need some guidance how to to do this. I can get the png logo of the channel from Lyngsat Logo. I have a VDR channels.conf channel list. I'm not sure if I can use the VDR channel list, but I would need an Enigma2 channel list (I can get those too).

Let's take an example, the channel "M1 HD".

Here is the png: http://www.lyngsat-logo.com/tvchannel/hu/M1-HD.html

The entry in my channels.conf is: 
M1 HD;RCS:11823:hC56M5O35S1:S0.8W:30000:4078=27:0;4102=hun@106:0:1802,1880,D97,653,1815,D02:4040:1:13:0 

This is the service reference from the E2 channels list:
1_0_1_FC8_D_1_E082E2F_0_0_0
(here I understand I will not need the 1_0_1_ and the _0_0_0 part)

With this given example, can somebody guide me step-by-step how can I add the channels (including black and white logo)? Once I have this, I will make this for all channels.

I'm using Kodi and VDR, but this doesn't matter in this case I guess, only when building.

Thanks!

**Comment by picons** [comment]
First download the project to you PC, save it in /tmp

Put you channels.conf inside /tmp/picons-source/build-input

Start the script /tmp/picons-source/1-build-servicelist.sh, choose the option "Service Reference"

When this script is finished, you get a file servicelist-vdr-srp inside /tmp/build-output

The file look like this https://gist.githubusercontent.com/picons/f7a16dcc8886367954ef/raw/c2d68acec3713c6df18a3eab88c10a69f1acd7c4/servicelist-enigma2-srp

Study this file, the last column is how your current channels.conf is linked with the logos inside this project, for you it will be mostly a lot of `FC8_D_1_E082E2F=--------`, to link that channel, you should add for example `FC8_D_1_E082E2F=tv/newfancychannel` to srp-index.

After you have added that to srp-index and you execute 1-build-servicelist.sh again, the file will no longer mention `FC8_D_1_E082E2F=--------`, but `FC8_D_1_E082E2F=tv/newfancychannel` instead.

I would focus first on adding all your channels for wich you can already find a logo inside /tmp/picons-source/build-source/tv and /tmp/picons-source/build-source/radio.

If you are good at it and you get how everything works, adding new logos is just the same, but you should add the correct logos, meaning give them appropiate names and make sure they are of the required quality, AND almost always use a svg instead of a png if you can find one.

**Comment by gurabli** [comment]
Thanks, this helps a lot!

Any ideas of a good place where can I look for svg logos?

Once I need to add a new logo, let's say png, how should I add it? I don't understand the part with white and black. Let's take the link of m1HD channel I posted from Lyngsat.
I understand now the naming.

**Comment by picons** [comment]
By searching on Google Images, you can add `filetype:svg`

Here's the svg version https://upload.wikimedia.org/wikipedia/commons/0/0a/Magyar_tv1_hd.svg

This particular logo will go in the `tv` folder and is called a black version, it looks good on a light background, now if you prefer using a dark background, you can make the black white, so that it will look good on a dark background, this logo will be placed in tv/white.

Most images you find online will look good on a lighter background, because they are designed for white webpages, so most of the time it requires some photoshop/gimp/inkscape work to make a white version.

A white version however is optional, if none is found the regular black one will be used.

If a white version is used/placed in /tv/white a black version must also exist in tv/

**Comment by gurabli** [comment]
So much thanks! Now I understand and I already have proper logos on Kodi. Some are outdated and some are missing. I will try to find the missing and update, add HD versions. Hard to find svg, and I need white, as I use them on black background, transparent versions. I will do some inkspace/ps and make these, just to find some time. I hope you can leave this open, as it might help others too, as it did for me.

**Comment by picons** [comment]
Most of it can be found here https://github.com/picons/picons-source/blob/master/CONTRIBUTING.md
and by browsing the actual code in most cases people figure out what to do.
